import type { AppState } from '../types';

const now = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return fmt(d);
};
const daysFromNow = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return fmt(d);
};
const monthsFromNow = (n: number) => {
  const d = new Date(now);
  d.setMonth(d.getMonth() + n);
  return fmt(d);
};

export const initialState: AppState = {
  funds: [
    { id: 1, name: 'needs', balance: 42500, allocation_pct: 50, color: '#FF2A2A' },
    { id: 2, name: 'wants', balance: 14800, allocation_pct: 20, color: '#A78BFA' },
    { id: 3, name: 'savings', balance: 31500, allocation_pct: 30, color: '#4ADE80' },
  ],
  transactions: [
    {
      id: 1001,
      type: 'income',
      name: 'Monthly Salary',
      amount: 80000,
      income_type: 'monthly',
      category: 'salary',
      date: daysAgo(28),
      notes: '',
      fund_allocation: { needs: 40000, wants: 16000, savings: 24000 },
    },
    {
      id: 1002,
      type: 'expense',
      description: 'Rent payment',
      amount: 20000,
      category: 'Rent',
      fund_id: 1,
      fund_name: 'needs',
      planned: true,
      date: daysAgo(26),
    },
    {
      id: 1003,
      type: 'expense',
      description: 'Groceries',
      amount: 3200,
      category: 'Groceries',
      fund_id: 1,
      fund_name: 'needs',
      planned: true,
      date: daysAgo(22),
    },
    {
      id: 1004,
      type: 'expense',
      description: 'Electricity bill',
      amount: 1500,
      category: 'Utilities',
      fund_id: 1,
      fund_name: 'needs',
      planned: true,
      date: daysAgo(18),
    },
    {
      id: 1005,
      type: 'expense',
      description: 'Netflix subscription',
      amount: 649,
      category: 'Subscriptions',
      fund_id: 2,
      fund_name: 'wants',
      planned: true,
      date: daysAgo(20),
    },
    {
      id: 1006,
      type: 'expense',
      description: 'Dinner at Barbeque Nation',
      amount: 2400,
      category: 'Dining Out',
      fund_id: 2,
      fund_name: 'wants',
      planned: false,
      date: daysAgo(15),
    },
    {
      id: 1007,
      type: 'expense',
      description: 'Fuel',
      amount: 2000,
      category: 'Transport',
      fund_id: 1,
      fund_name: 'needs',
      planned: false,
      date: daysAgo(12),
    },
    {
      id: 1008,
      type: 'expense',
      description: 'Movie tickets',
      amount: 800,
      category: 'Entertainment',
      fund_id: 2,
      fund_name: 'wants',
      planned: false,
      date: daysAgo(10),
    },
    {
      id: 1009,
      type: 'income',
      name: 'Freelance — logo design',
      amount: 12000,
      income_type: 'irregular',
      category: 'freelance',
      date: daysAgo(8),
      notes: 'Client: Acme Corp',
      fund_allocation: { needs: 6000, wants: 2400, savings: 3600 },
    },
    {
      id: 1010,
      type: 'expense',
      description: 'SIP — HDFC Mid-Cap',
      amount: 5000,
      category: 'Investments',
      fund_id: 3,
      fund_name: 'savings',
      planned: true,
      date: daysAgo(7),
    },
    {
      id: 1011,
      type: 'expense',
      description: 'New running shoes',
      amount: 4500,
      category: 'Shopping',
      fund_id: 2,
      fund_name: 'wants',
      planned: false,
      date: daysAgo(5),
    },
    {
      id: 1012,
      type: 'expense',
      description: 'Internet bill',
      amount: 1100,
      category: 'Utilities',
      fund_id: 1,
      fund_name: 'needs',
      planned: true,
      date: daysAgo(3),
    },
    {
      id: 1013,
      type: 'expense',
      description: 'Gym membership',
      amount: 2500,
      category: 'Health',
      fund_id: 1,
      fund_name: 'needs',
      planned: true,
      date: daysAgo(1),
    },
  ],
  wants: [
    {
      id: 2001,
      name: 'iPhone 16 Pro',
      target_price: 134900,
      current_saved: 45200,
      category: 'electronics',
      priority: 2,
      purchased: false,
      purchase_date: null,
      notes: 'Pro Max 256GB',
      days_to_buy: 56,
      predicted_date: monthsFromNow(2),
      photo_url: null,
      purchase_link: 'https://www.flipkart.com/apple-iphone-16-pro',
    },
    {
      id: 2002,
      name: 'Mechanical Keyboard',
      target_price: 8500,
      current_saved: 6000,
      category: 'electronics',
      priority: 1,
      purchased: false,
      purchase_date: null,
      notes: 'Keychron Q1',
      days_to_buy: 15,
      predicted_date: daysFromNow(15),
      photo_url: null,
      purchase_link: 'https://www.keychron.com/products/keychron-q1',
    },
    {
      id: 2003,
      name: 'Goa Trip',
      target_price: 45000,
      current_saved: 12000,
      category: 'travel',
      priority: 1,
      purchased: false,
      purchase_date: null,
      notes: '3 nights, December',
      days_to_buy: 130,
      predicted_date: monthsFromNow(4),
      photo_url: null,
      purchase_link: null,
    },
    {
      id: 2004,
      name: 'Standing Desk',
      target_price: 22000,
      current_saved: 22000,
      category: 'furniture',
      priority: 0,
      purchased: true,
      purchase_date: daysAgo(14),
      notes: 'Fezibo electric',
      days_to_buy: null,
      predicted_date: null,
      photo_url: null,
      purchase_link: null,
    },
  ],
  needs: [
    {
      id: 3001,
      name: 'Rent',
      amount: 20000,
      category: 'Housing',
      recurring: true,
      frequency: 'monthly',
      due_date: '1st of each month',
      fund_id: 1,
      fund_name: 'needs',
      autopay: true,
      notes: '',
      active: true,
    },
    {
      id: 3002,
      name: 'Internet',
      amount: 1100,
      category: 'Utilities',
      recurring: true,
      frequency: 'monthly',
      due_date: '5th of each month',
      fund_id: 1,
      fund_name: 'needs',
      autopay: false,
      notes: 'Airtel Xstream 150Mbps',
      active: true,
    },
    {
      id: 3003,
      name: 'Gym',
      amount: 2500,
      category: 'Health',
      recurring: true,
      frequency: 'monthly',
      due_date: '10th of each month',
      fund_id: 1,
      fund_name: 'needs',
      autopay: true,
      notes: 'Cult.fit',
      active: true,
    },
    {
      id: 3004,
      name: 'Car Insurance',
      amount: 18000,
      category: 'Insurance',
      recurring: true,
      frequency: 'yearly',
      due_date: 'March 15',
      fund_id: 1,
      fund_name: 'needs',
      autopay: false,
      notes: 'Comprehensive policy',
      active: true,
    },
    {
      id: 3005,
      name: 'Laptop Repair',
      amount: 8000,
      category: 'Repair',
      recurring: false,
      frequency: null,
      due_date: '2025-08-01',
      fund_id: 1,
      fund_name: 'needs',
      autopay: false,
      notes: 'Screen replacement',
      active: true,
    },
  ],
  investments: [
    {
      id: 4001,
      name: 'Reliance Industries',
      asset_type: 'stock',
      invest_amount: 50000,
      current_value: 64500,
      purchase_date: '2025-01-15',
      notes: '40 shares',
    },
    {
      id: 4002,
      name: 'HDFC Mid-Cap Fund',
      asset_type: 'mutual_fund',
      invest_amount: 120000,
      current_value: 148000,
      purchase_date: '2024-06-01',
      notes: 'SIP ₹5000/month',
    },
    {
      id: 4003,
      name: 'SBI Fixed Deposit',
      asset_type: 'fd',
      invest_amount: 200000,
      current_value: 218000,
      purchase_date: '2024-01-15',
      notes: '2 year FD at 7.1%',
    },
    {
      id: 4004,
      name: 'PPF Account',
      asset_type: 'ppf',
      invest_amount: 150000,
      current_value: 172000,
      purchase_date: '2023-04-01',
      notes: 'Annual ₹1.5L contribution',
    },
  ],
  reports: [],
  settings: {
    needs_pct: 50,
    wants_pct: 20,
    savings_pct: 30,
    currency: '₹',
    locale: 'en-IN',
  },
  loading: false,
};
